spring:
  application:
    name: cdn-frontend
  servlet:
    multipart:
      max-file-size: 2000MB
      max-request-size: 2000MB
coordinator:
  url: http://localhost:8761
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    ip-address: ${SERVICE_ADDRESS}